Variables:
  # Custom variables of ATrust Handysignatur API
  ATrust:
    # API Key for "A-Trust Handysignatur API"
    APIKey: 'TEST-API-KEY-UXWRZBKTTMQOFXFQFIUPABGUCZQGYTXDFPYTUOYRGIFQHKRELBR'

    # The endpoint uri of A-Trust Handysignatur Signatur-box webservice
    EndpointUri: 'https://handy-signatur.at/demosignaturbox/intern/HandySignaturPdf.svc'

    # The ID of the signature template to be used.
    TemplateId: 14464

