/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SignatureBatch
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureBatch {
  @JsonProperty("RedirectUrl")
  private String redirectUrl = null;

  @JsonProperty("ErrorUrl")
  private String errorUrl = null;

  public SignatureBatch redirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * URL to redirect to after a successful operation
   * @return redirectUrl
  **/
  public String getRedirectUrl() {
    return redirectUrl;
  }

  public void setRedirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }

  public SignatureBatch errorUrl(String errorUrl) {
    this.errorUrl = errorUrl;
    return this;
  }

   /**
   * URL to redirect to in case of an error
   * @return errorUrl
  **/
  public String getErrorUrl() {
    return errorUrl;
  }

  public void setErrorUrl(String errorUrl) {
    this.errorUrl = errorUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureBatch signatureBatch = (SignatureBatch) o;
    return Objects.equals(this.redirectUrl, signatureBatch.redirectUrl) &&
        Objects.equals(this.errorUrl, signatureBatch.errorUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redirectUrl, errorUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureBatch {\n");
    
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("    errorUrl: ").append(toIndentedString(errorUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
