/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import at.a.trust.rest.api.client.SignatureCertificateIssuedTo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SignatureCertificate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureCertificate {
  @JsonProperty("certificate")
  private String certificate = null;

  @JsonProperty("issuedTo")
  private SignatureCertificateIssuedTo issuedTo = null;

  public SignatureCertificate certificate(String certificate) {
    this.certificate = certificate;
    return this;
  }

   /**
   * The certificate associated with the signature batch
   * @return certificate
  **/
  public String getCertificate() {
    return certificate;
  }

  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }

  public SignatureCertificate issuedTo(SignatureCertificateIssuedTo issuedTo) {
    this.issuedTo = issuedTo;
    return this;
  }

   /**
   * Get issuedTo
   * @return issuedTo
  **/
  public SignatureCertificateIssuedTo getIssuedTo() {
    return issuedTo;
  }

  public void setIssuedTo(SignatureCertificateIssuedTo issuedTo) {
    this.issuedTo = issuedTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureCertificate signatureCertificate = (SignatureCertificate) o;
    return Objects.equals(this.certificate, signatureCertificate.certificate) &&
        Objects.equals(this.issuedTo, signatureCertificate.issuedTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificate, issuedTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureCertificate {\n");
    
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    issuedTo: ").append(toIndentedString(issuedTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
