/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SignatureTemplateFieldsLabel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureTemplateFieldsLabel {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("x")
  private Float x = null;

  @JsonProperty("y")
  private Float y = null;

  @JsonProperty("w")
  private Float w = null;

  @JsonProperty("h")
  private Float h = null;

  @JsonProperty("center")
  private Boolean center = null;

  @JsonProperty("wrap")
  private Boolean wrap = null;

  @JsonProperty("fgColor")
  private String fgColor = null;

  @JsonProperty("bgColor")
  private String bgColor = null;

  @JsonProperty("textSize")
  private Integer textSize = null;

  public SignatureTemplateFieldsLabel type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SignatureTemplateFieldsLabel x(Float x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/
  public Float getX() {
    return x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  public SignatureTemplateFieldsLabel y(Float y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/
  public Float getY() {
    return y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  public SignatureTemplateFieldsLabel w(Float w) {
    this.w = w;
    return this;
  }

   /**
   * Get w
   * @return w
  **/
  public Float getW() {
    return w;
  }

  public void setW(Float w) {
    this.w = w;
  }

  public SignatureTemplateFieldsLabel h(Float h) {
    this.h = h;
    return this;
  }

   /**
   * Get h
   * @return h
  **/
  public Float getH() {
    return h;
  }

  public void setH(Float h) {
    this.h = h;
  }

  public SignatureTemplateFieldsLabel center(Boolean center) {
    this.center = center;
    return this;
  }

   /**
   * Get center
   * @return center
  **/
  public Boolean isCenter() {
    return center;
  }

  public void setCenter(Boolean center) {
    this.center = center;
  }

  public SignatureTemplateFieldsLabel wrap(Boolean wrap) {
    this.wrap = wrap;
    return this;
  }

   /**
   * Get wrap
   * @return wrap
  **/
  public Boolean isWrap() {
    return wrap;
  }

  public void setWrap(Boolean wrap) {
    this.wrap = wrap;
  }

  public SignatureTemplateFieldsLabel fgColor(String fgColor) {
    this.fgColor = fgColor;
    return this;
  }

   /**
   * Get fgColor
   * @return fgColor
  **/
  public String getFgColor() {
    return fgColor;
  }

  public void setFgColor(String fgColor) {
    this.fgColor = fgColor;
  }

  public SignatureTemplateFieldsLabel bgColor(String bgColor) {
    this.bgColor = bgColor;
    return this;
  }

   /**
   * Get bgColor
   * @return bgColor
  **/
  public String getBgColor() {
    return bgColor;
  }

  public void setBgColor(String bgColor) {
    this.bgColor = bgColor;
  }

  public SignatureTemplateFieldsLabel textSize(Integer textSize) {
    this.textSize = textSize;
    return this;
  }

   /**
   * Get textSize
   * @return textSize
  **/
  public Integer getTextSize() {
    return textSize;
  }

  public void setTextSize(Integer textSize) {
    this.textSize = textSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTemplateFieldsLabel signatureTemplateFieldsLabel = (SignatureTemplateFieldsLabel) o;
    return Objects.equals(this.type, signatureTemplateFieldsLabel.type) &&
        Objects.equals(this.x, signatureTemplateFieldsLabel.x) &&
        Objects.equals(this.y, signatureTemplateFieldsLabel.y) &&
        Objects.equals(this.w, signatureTemplateFieldsLabel.w) &&
        Objects.equals(this.h, signatureTemplateFieldsLabel.h) &&
        Objects.equals(this.center, signatureTemplateFieldsLabel.center) &&
        Objects.equals(this.wrap, signatureTemplateFieldsLabel.wrap) &&
        Objects.equals(this.fgColor, signatureTemplateFieldsLabel.fgColor) &&
        Objects.equals(this.bgColor, signatureTemplateFieldsLabel.bgColor) &&
        Objects.equals(this.textSize, signatureTemplateFieldsLabel.textSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, x, y, w, h, center, wrap, fgColor, bgColor, textSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateFieldsLabel {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    center: ").append(toIndentedString(center)).append("\n");
    sb.append("    wrap: ").append(toIndentedString(wrap)).append("\n");
    sb.append("    fgColor: ").append(toIndentedString(fgColor)).append("\n");
    sb.append("    bgColor: ").append(toIndentedString(bgColor)).append("\n");
    sb.append("    textSize: ").append(toIndentedString(textSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
