/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SignatureTemplatePosition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureTemplatePosition {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("x")
  private Float x = null;

  @JsonProperty("y")
  private Float y = null;

  @JsonProperty("w")
  private Float w = null;

  @JsonProperty("h")
  private Float h = null;

  @JsonProperty("page")
  private Integer page = null;

  public SignatureTemplatePosition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SignatureTemplatePosition x(Float x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/
  public Float getX() {
    return x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  public SignatureTemplatePosition y(Float y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/
  public Float getY() {
    return y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  public SignatureTemplatePosition w(Float w) {
    this.w = w;
    return this;
  }

   /**
   * Get w
   * @return w
  **/
  public Float getW() {
    return w;
  }

  public void setW(Float w) {
    this.w = w;
  }

  public SignatureTemplatePosition h(Float h) {
    this.h = h;
    return this;
  }

   /**
   * Get h
   * @return h
  **/
  public Float getH() {
    return h;
  }

  public void setH(Float h) {
    this.h = h;
  }

  public SignatureTemplatePosition page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTemplatePosition signatureTemplatePosition = (SignatureTemplatePosition) o;
    return Objects.equals(this.type, signatureTemplatePosition.type) &&
        Objects.equals(this.x, signatureTemplatePosition.x) &&
        Objects.equals(this.y, signatureTemplatePosition.y) &&
        Objects.equals(this.w, signatureTemplatePosition.w) &&
        Objects.equals(this.h, signatureTemplatePosition.h) &&
        Objects.equals(this.page, signatureTemplatePosition.page);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, x, y, w, h, page);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplatePosition {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
