/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SignatureCertificateIssuedTo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureCertificateIssuedTo {
  @JsonProperty("country")
  private String country = null;

  @JsonProperty("stateOrProvince")
  private String stateOrProvince = null;

  @JsonProperty("locality")
  private String locality = null;

  @JsonProperty("organization")
  private String organization = null;

  @JsonProperty("commonName")
  private String commonName = null;

  @JsonProperty("alternativeNames")
  private String alternativeNames = null;

  public SignatureCertificateIssuedTo country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public SignatureCertificateIssuedTo stateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
    return this;
  }

   /**
   * Get stateOrProvince
   * @return stateOrProvince
  **/
  public String getStateOrProvince() {
    return stateOrProvince;
  }

  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public SignatureCertificateIssuedTo locality(String locality) {
    this.locality = locality;
    return this;
  }

   /**
   * Get locality
   * @return locality
  **/
  public String getLocality() {
    return locality;
  }

  public void setLocality(String locality) {
    this.locality = locality;
  }

  public SignatureCertificateIssuedTo organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public SignatureCertificateIssuedTo commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * Get commonName
   * @return commonName
  **/
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public SignatureCertificateIssuedTo alternativeNames(String alternativeNames) {
    this.alternativeNames = alternativeNames;
    return this;
  }

   /**
   * Get alternativeNames
   * @return alternativeNames
  **/
  public String getAlternativeNames() {
    return alternativeNames;
  }

  public void setAlternativeNames(String alternativeNames) {
    this.alternativeNames = alternativeNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureCertificateIssuedTo signatureCertificateIssuedTo = (SignatureCertificateIssuedTo) o;
    return Objects.equals(this.country, signatureCertificateIssuedTo.country) &&
        Objects.equals(this.stateOrProvince, signatureCertificateIssuedTo.stateOrProvince) &&
        Objects.equals(this.locality, signatureCertificateIssuedTo.locality) &&
        Objects.equals(this.organization, signatureCertificateIssuedTo.organization) &&
        Objects.equals(this.commonName, signatureCertificateIssuedTo.commonName) &&
        Objects.equals(this.alternativeNames, signatureCertificateIssuedTo.alternativeNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, stateOrProvince, locality, organization, commonName, alternativeNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureCertificateIssuedTo {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    alternativeNames: ").append(toIndentedString(alternativeNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
