/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import at.a.trust.rest.api.client.TemplateMeta;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * SignatureTemplates
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureTemplates {
  @JsonProperty("templateList")
  private List<TemplateMeta> templateList = new ArrayList<>();

  public SignatureTemplates templateList(List<TemplateMeta> templateList) {
    this.templateList = templateList;
    return this;
  }

  public SignatureTemplates addTemplateListItem(TemplateMeta templateListItem) {
    this.templateList.add(templateListItem);
    return this;
  }

   /**
   * Get templateList
   * @return templateList
  **/
  public List<TemplateMeta> getTemplateList() {
    return templateList;
  }

  public void setTemplateList(List<TemplateMeta> templateList) {
    this.templateList = templateList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTemplates signatureTemplates = (SignatureTemplates) o;
    return Objects.equals(this.templateList, signatureTemplates.templateList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplates {\n");
    
    sb.append("    templateList: ").append(toIndentedString(templateList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
