/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import at.a.trust.rest.api.client.SignatureTemplateFieldsLabel;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * SignatureTemplateFields
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureTemplateFields {
  @JsonProperty("Label")
  private List<SignatureTemplateFieldsLabel> label = new ArrayList<>();

  public SignatureTemplateFields label(List<SignatureTemplateFieldsLabel> label) {
    this.label = label;
    return this;
  }

  public SignatureTemplateFields addLabelItem(SignatureTemplateFieldsLabel labelItem) {
    this.label.add(labelItem);
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  public List<SignatureTemplateFieldsLabel> getLabel() {
    return label;
  }

  public void setLabel(List<SignatureTemplateFieldsLabel> label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTemplateFields signatureTemplateFields = (SignatureTemplateFields) o;
    return Objects.equals(this.label, signatureTemplateFields.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateFields {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
