/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import at.a.trust.rest.api.client.SignatureTemplateDescription;
import at.a.trust.rest.api.client.SignatureTemplateFields;
import at.a.trust.rest.api.client.SignatureTemplatePosition;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SignatureTemplate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignatureTemplate {
  @JsonProperty("Description")
  private SignatureTemplateDescription description = null;

  @JsonProperty("Position")
  private SignatureTemplatePosition position = null;

  @JsonProperty("B64bgImage")
  private String b64bgImage = null;

  @JsonProperty("Fields")
  private SignatureTemplateFields fields = null;

  public SignatureTemplate description(SignatureTemplateDescription description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public SignatureTemplateDescription getDescription() {
    return description;
  }

  public void setDescription(SignatureTemplateDescription description) {
    this.description = description;
  }

  public SignatureTemplate position(SignatureTemplatePosition position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  public SignatureTemplatePosition getPosition() {
    return position;
  }

  public void setPosition(SignatureTemplatePosition position) {
    this.position = position;
  }

  public SignatureTemplate b64bgImage(String b64bgImage) {
    this.b64bgImage = b64bgImage;
    return this;
  }

   /**
   * Get b64bgImage
   * @return b64bgImage
  **/
  public String getB64bgImage() {
    return b64bgImage;
  }

  public void setB64bgImage(String b64bgImage) {
    this.b64bgImage = b64bgImage;
  }

  public SignatureTemplate fields(SignatureTemplateFields fields) {
    this.fields = fields;
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  public SignatureTemplateFields getFields() {
    return fields;
  }

  public void setFields(SignatureTemplateFields fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTemplate signatureTemplate = (SignatureTemplate) o;
    return Objects.equals(this.description, signatureTemplate.description) &&
        Objects.equals(this.position, signatureTemplate.position) &&
        Objects.equals(this.b64bgImage, signatureTemplate.b64bgImage) &&
        Objects.equals(this.fields, signatureTemplate.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, position, b64bgImage, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplate {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    b64bgImage: ").append(toIndentedString(b64bgImage)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
