/*
 * A-Trust Connector API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.a.trust.rest.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.File;
/**
 * SignDocument
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-30T11:57:03.289800600+07:00[Asia/Bangkok]")

public class SignDocument {
  @JsonProperty("document")
  private File document = null;

  @JsonProperty("location")
  private String location = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("template")
  private String template = null;

  @JsonProperty("page")
  private String page = null;

  @JsonProperty("x")
  private String x = null;

  @JsonProperty("y")
  private String y = null;

  @JsonProperty("w")
  private String w = null;

  @JsonProperty("h")
  private String h = null;

  public SignDocument document(File document) {
    this.document = document;
    return this;
  }

   /**
   * The document to be signed
   * @return document
  **/
  public File getDocument() {
    return document;
  }

  public void setDocument(File document) {
    this.document = document;
  }

  public SignDocument location(String location) {
    this.location = location;
    return this;
  }

   /**
   * The location related to the document
   * @return location
  **/
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public SignDocument reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * The reason for signing the document
   * @return reason
  **/
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public SignDocument template(String template) {
    this.template = template;
    return this;
  }

   /**
   * The templateID of the template that should be used
   * @return template
  **/
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public SignDocument page(String page) {
    this.page = page;
    return this;
  }

   /**
   * page of the signature seal
   * @return page
  **/
  public String getPage() {
    return page;
  }

  public void setPage(String page) {
    this.page = page;
  }

  public SignDocument x(String x) {
    this.x = x;
    return this;
  }

   /**
   * x0 coordinate in userspace units
   * @return x
  **/
  public String getX() {
    return x;
  }

  public void setX(String x) {
    this.x = x;
  }

  public SignDocument y(String y) {
    this.y = y;
    return this;
  }

   /**
   * y0 coordinate in userspace units
   * @return y
  **/
  public String getY() {
    return y;
  }

  public void setY(String y) {
    this.y = y;
  }

  public SignDocument w(String w) {
    this.w = w;
    return this;
  }

   /**
   * x1 coordinate in userspace units
   * @return w
  **/
  public String getW() {
    return w;
  }

  public void setW(String w) {
    this.w = w;
  }

  public SignDocument h(String h) {
    this.h = h;
    return this;
  }

   /**
   * y1 coordinate in userspace units
   * @return h
  **/
  public String getH() {
    return h;
  }

  public void setH(String h) {
    this.h = h;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignDocument signDocument = (SignDocument) o;
    return Objects.equals(this.document, signDocument.document) &&
        Objects.equals(this.location, signDocument.location) &&
        Objects.equals(this.reason, signDocument.reason) &&
        Objects.equals(this.template, signDocument.template) &&
        Objects.equals(this.page, signDocument.page) &&
        Objects.equals(this.x, signDocument.x) &&
        Objects.equals(this.y, signDocument.y) &&
        Objects.equals(this.w, signDocument.w) &&
        Objects.equals(this.h, signDocument.h);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document), location, reason, template, page, x, y, w, h);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignDocument {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
