name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci-fork.yml
    with:
      mvnArgs: '-Dproject.build.plugin.version=11.4.0-SNAPSHOT -Dtester.version=11.4.0-SNAPSHOT'
      javaVersion: 21
      mvnVersion: '3.9.8'
