name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    permissions:
      contents: read
      actions: write
      checks: write
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v6
    secrets:
      mvnArgs: -Datrust.apiKey=${{secrets.API_KEY}} -Datrust.serverUrl=${{secrets.SERVER_URL}} -Datrust.signBox=${{secrets.SIGN_BOX}}