name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v4
    with:
      # temporary: disable script validation ... connector uses a variable not compatible with 11.4!
      mvnArgs: '-Divy.script.validation.skip=true'
      # temporary: use 11.3 until root cause of failing tests on 11.4 is known
      ivyPluginVersion: 11.3.0
      testerVersion: 11.3.0
      ivyVersion: nightly-11.3
